<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetTestVersion)</TargetFramework>
    <RootNamespace>P99.QuickStart</RootNamespace>
    <AssemblyName>P99.QuickStart</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\P99\P99.csproj" />
  </ItemGroup>

</Project>
